### ISSUE TITLE
read me

### ISSUE THREAD

**Issue by MareoRaft** [CoronaOpenSource/CoronaOpenSource.github.io-old#10]
What is the purpose of this project?  Do you need any help?

**Comment by AJamesPhillips** [comment]
Thanks @MareoRaft   It was started on the naive assumption that companies would realise the gravity of the situation and open up their IP for others to copy so that we can get out of the situation and back to a "normal" society.

https://www.linkedin.com/posts/ajamesphillips_corona-qiagen-roche-activity-6648943480796172288-eaiZ
https://www.linkedin.com/posts/ajamesphillips_world-health-organization-who-on-twitter-activity-6649723353101848576-BvA3
https://www.linkedin.com/posts/ajamesphillips_register-to-download-ventilator-files-activity-6650830353093189633-fvsx

It contains a couple of open source licences (not drafted by me) but github pages is not working so you can't see them via http://coronaopensource.org/licences at the moment.  It's newest incarnation is: https://opencovidpledge.org/

**Comment by MareoRaft** [comment]
Hm.  It looks like it didn't catch on as much as you wanted, but you did get some big company names there.

**Comment by MareoRaft** [comment]
@AJamesPhillips I opened PR #12 if it helps you out.

**Comment by MareoRaft** [comment]
Let me know if there's anything more i can help with

**Comment by AJamesPhillips** [comment]
Regarding: https://github.com/CoronaOpenSource/CoronaOpenSource.github.io/issues/10#issuecomment-611768867

It's still very much a work in progress :)  Lots of activity behind the scenes by the amazing team there (lawyers and people with connections doing the heavy lifting now :) )
